### ISSUE TITLE
Typo in a quote

### ISSUE THREAD

**Issue by MDM23** [tomlutzenberger/id-software-programming-principles#1]
Hi Tom 😉 

I think you got a typo in one of the quotes at https://github.com/tomlutzenberger/id-software-programming-principles/blob/73e633e3b89e465d18b7679ced5f4379e13cd019/index.pug#L111

> Do not treat game programming like each coder is a **bloack** box

**Comment by tomlutzenberger** [comment]
Fixed. Thanks a lot 😁
